source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SwiftKeepLayout_Tests', :exclusive => true do
  pod 'SwiftKeepLayout', :path => '../'

  
end

pod 'KeepLayout', :git => 'https://github.com/Tricertops/KeepLayout.git', :branch => 'swift-legacy'
